# Generated by Django 4.2.4 on 2023-10-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
