# Generated by Django 4.2.4 on 2023-09-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcompanies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commpany',
            new_name='Company',
        ),
    ]
