# Generated by Django 4.2.4 on 2023-10-06 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcompanies', '0002_rename_commpany_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companies', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='employee',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcompanies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='escliente',
            field=models.BooleanField(default=False),
        ),
    ]
